services:
  - type: web
    name: chatkin-ai
    env: node
    plan: free
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: node server/server.js
    envVars:
      - key: NODE_VERSION
        value: 20
