services:
  - type: web
    name: ChatKin-AI
    env: node
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: node server/index.js
    plan: free
    region: oregon
